Repository dxc-technology/halstack-react, pull requests merged in 2021-05, with the labels that each got.

#287 [Minor] Advanced tokens for Alert component
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/Mode.jsx
  docs/src/pages/themeBuilder/components/previews/Alert.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/alert/Alert.jsx
  lib/src/common/variables.js
Labels: [PR] status: approved

#294 [Minor] Advanced tokens for Chip component
  docs/src/pages/themeBuilder/components/previews/Chip.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/ThemeContext.js
  lib/src/chip/Chip.jsx
  lib/src/common/variables.js
Labels: [PR] status: approved

#296 [Minor] Advanced tokens for Dropdown component
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/ThemeContext.js
  lib/src/common/variables.js
  lib/src/dropdown/Dropdown.jsx
Labels: [PR] status: approved

#297 [Minor] Advanced tokens for Dialog component
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/previews/Dialog.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/button/Button.jsx
  lib/src/common/variables.js
  lib/src/dialog/Dialog.jsx
  lib/src/layout/ApplicationLayout.jsx
Labels: [PR] status: approved

#298 [Minor] Advanced tokens for radio component
  docs/src/pages/themeBuilder/components/previews/RadioButton.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/radio/Radio.jsx
Labels: [PR] status: approved

#302 [Minor] Advanced tokens for Textarea component
  docs/src/pages/themeBuilder/components/ComponentPreview.jsx
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/previews/Textarea.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/textarea/Textarea.jsx
Labels: [PR] status: approved

#303 [Minor] Advanced tokens for Checkbox component
  docs/src/pages/themeBuilder/components/previews/Checkbox.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/checkbox/Checkbox.jsx
  lib/src/common/variables.js
Labels: [PR] status: approved

#304 [Minor] Advanced tokens for select component
  docs/src/pages/themeBuilder/components/previews/Select.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/select/Select.jsx
Labels: [PR] status: approved

#305 [Minor] Advanced tokens for Upload component
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/previews/Upload.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/spinner/Spinner.jsx
  lib/src/upload/Upload.jsx
  lib/src/upload/buttons-upload/ButtonsUpload.jsx
  lib/src/upload/dragAndDropArea/DragAndDropArea.jsx
  lib/src/upload/file-upload/FileToUpload.jsx
  lib/src/upload/files-upload/FilesToUpload.jsx
  lib/src/upload/transaction/Transaction.jsx
  lib/src/upload/transactions/Transactions.jsx
Labels: [PR] status: approved

#306 [Minor] Advanced tokens for tag component
  docs/src/pages/components/cdk-components/tag/api.jsx
  docs/src/pages/components/cdk-components/tag/examples/basicExample.js
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/previews/Tag.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/tag/Tag.jsx
Labels: [PR] status: approved

#307 [Minor] Advanced tokens for Slider component
  docs/src/pages/themeBuilder/ThemeBuilder.jsx
  docs/src/pages/themeBuilder/components/previews/Slider.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/ThemeContext.js
  lib/src/common/variables.js
  lib/src/slider/Slider.jsx
Labels: [PR] status: approved

#289 [Minor] Advanced tokens for input component
  docs/src/pages/themeBuilder/components/ComponentsPreviewMap.js
  docs/src/pages/themeBuilder/components/previews/InputText.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/input-text/InputText.jsx
Labels: [PR] status: pending review

#301 [Minor] Advanced tokens for resultset table component
  docs/src/pages/themeBuilder/components/previews/Table.jsx
  docs/src/pages/themeBuilder/themes/AdvancedTheme.json
  docs/src/pages/themeBuilder/themes/schemas/Advanced.schema.json
  lib/src/common/variables.js
  lib/src/resultsetTable/ResultsetTable.jsx
  lib/src/table/Table.jsx
Labels: [PR] status: change request

#311 Improved import functionality in theme-builder
  docs/src/pages/themeBuilder/ImportDialog.jsx
  docs/src/pages/themeBuilder/ThemeBuilder.jsx
  docs/src/pages/themeBuilder/themes/DefaultTheme.json
Labels: enhancement
