Repository dxc-technology/halstack-react, pull requests merged in 2022-02, with the labels that each got.

#566 Added box stories
  lib/.storybook/preview.js
  lib/src/box/Box.stories.jsx
Labels: [PR] type: visual regression

#571 Added number input stories
  lib/src/number-input/NumberInput.stories.jsx
Labels: [PR] type: visual regression

#595 SVG type update
  lib/src/accordion-group/types.ts
  lib/src/accordion/types.ts
  lib/src/select/index.d.ts
  lib/src/text-input/index.d.ts
Labels: [PR] type: Type API

#612 Types for Dialog component
  docs/src/pages/components/cdk-components/dialog/api.jsx
  lib/src/dialog/Dialog.tsx
  lib/src/dialog/index.d.ts
  lib/src/dialog/types.ts
Labels: [PR] type: Type API

#603 Added footer stories
  lib/src/footer/Footer.stories.jsx
Labels: [PR] type: visual regression

#621 Added Paginator stories
  lib/src/paginator/Paginator.stories.tsx
Labels: [PR] type: visual regression

#604 Added table stories
  lib/src/table/Table.stories.jsx
Labels: [PR] type: visual regression

#609 [Patch] Fixed margin with overlay in spinner
  lib/src/spinner/Spinner.jsx
Labels: bug

#611 [Patch] Fixed token font family in ProgressBar
  lib/src/progress-bar/ProgressBar.tsx
Labels: bug

#617 Added spinner stories
  lib/src/spinner/Spinner.stories.jsx
Labels: [PR] type: visual regression

#581 Types for Header component
  docs/src/pages/components/cdk-components/header/api.jsx
  lib/src/header/Header.tsx
  lib/src/header/Icons.jsx
  lib/src/header/index.d.ts
  lib/src/header/types.ts
Labels: [PR] type: Type API

#602 Added Radio stories
  lib/src/radio/Radio.stories.tsx
Labels: [PR] type: visual regression

#587 Types for Table component
  docs/src/pages/components/cdk-components/table/api.jsx
  lib/src/table/Table.tsx
  lib/src/table/index.d.ts
  lib/src/table/types.ts
Labels: [PR] type: Type API

#590 Types for Spinner component
  lib/src/spinner/Spinner.tsx
  lib/src/spinner/index.d.ts
  lib/src/spinner/types.ts
Labels: [PR] type: Type API

#626 Added button types
  docs/src/pages/components/cdk-components/button/api.jsx
  lib/src/button/Button.tsx
  lib/src/button/types.ts
Labels: [PR] type: Type API

#620 Added tag stories
  lib/src/button/Button.stories.tsx
  lib/src/password-input/PasswordInput.stories.jsx
  lib/src/tag/Tag.jsx
  lib/src/tag/Tag.stories.jsx
Labels: [PR] type: visual regression

#615 Types for Link component
  docs/src/pages/components/cdk-components/link/api.jsx
  lib/src/link/Link.tsx
  lib/src/link/index.d.ts
  lib/src/link/types.ts
Labels: [PR] type: Type API

#632 Added password types
  docs/src/pages/components/cdk-components/password-input/api.jsx
  lib/src/password-input/PasswordInput.stories.tsx
  lib/src/password-input/PasswordInput.tsx
  lib/src/password-input/types.ts
Labels: [PR] type: Type API

#614 Add Switch stories and update component styles
  lib/src/common/variables.js
  lib/src/switch/Switch.stories.tsx
  lib/src/switch/Switch.tsx
Labels: [PR] type: visual regression

#596 Added progressbar stories
  lib/src/progress-bar/ProgressBar.stories.jsx
Labels: [PR] type: visual regression

#644 Added box types
  docs/src/pages/components/cdk-components/box/api.jsx
  lib/src/box/Box.stories.tsx
  lib/src/box/Box.tsx
  lib/src/box/index.d.ts
  lib/src/box/types.ts
Labels: [PR] type: Type API

#647 Added tag types.
  docs/src/pages/components/cdk-components/tag/api.jsx
  lib/src/tag/Tag.stories.tsx
  lib/src/tag/Tag.tsx
  lib/src/tag/index.d.ts
  lib/src/tag/types.ts
Labels: [PR] type: Type API

#638 Added number types
  lib/src/number-input/NumberInput.stories.tsx
  lib/src/number-input/NumberInput.tsx
  lib/src/number-input/types.ts
Labels: [PR] type: Type API

#643 Added wizard types
  docs/src/pages/components/cdk-components/wizard/api.jsx
  lib/src/wizard/Wizard.tsx
  lib/src/wizard/index.d.ts
  lib/src/wizard/types.ts
Labels: [PR] type: Type API

#625 Added ToggleGroup stories
  lib/src/toggle-group/ToggleGroup.stories.tsx
Labels: [PR] type: visual regression

#622 Added Select stories
  lib/src/select/Select.stories.tsx
Labels: [PR] type: visual regression

#646 Added wizard stories
  lib/src/wizard/Wizard.stories.jsx
Labels: [PR] type: visual regression

#613 Adding dialog stories
  lib/src/dialog/Dialog.stories.tsx
Labels: [PR] type: visual regression

#636 Added Chip stories
  lib/src/chip/Chip.stories.tsx
Labels: [PR] type: visual regression

#661 Types for Heading component
  docs/src/pages/components/cdk-components/heading/examples/asHeadings.js
  lib/src/heading/Heading.tsx
  lib/src/heading/index.d.ts
  lib/src/heading/types.ts
Labels: [PR] type: Type API

#668 [Patch] Marked children as optional in footer
  lib/src/footer/types.ts
Labels: bug

#660 Added Header stories
  lib/src/header/Header.stories.tsx
Labels: [PR] type: visual regression

#664 Added file input types.
  docs/src/pages/components/cdk-components/file-input/api.jsx
  lib/src/file-input/FileInput.tsx
  lib/src/file-input/FileItem.tsx
  lib/src/file-input/types.ts
Labels: [PR] type: Type API

#670 [Patch] Card outlined prop fix and focus style
  docs/src/pages/components/cdk-components/card/api.jsx
  lib/src/card/Card.tsx
Labels: bug

#618 Added Card stories
  lib/src/card/Card.stories.tsx
  lib/src/card/ice-cream.jpg
Labels: [PR] type: visual regression

#678 Fix type comments indicating margin values
  lib/src/alert/types.ts
  lib/src/card/types.ts
  lib/src/checkbox/types.ts
  lib/src/header/types.ts
  lib/src/radio/types.ts
  lib/src/tabs/types.ts
Labels: documentation

#662 Added Heading stories
  lib/src/heading/Heading.stories.tsx
Labels: [PR] type: visual regression

#637 Added Sidenav stories
  lib/src/sidenav/Sidenav.stories.tsx
Labels: [PR] type: visual regression

#659 [Patch] Disabled tabs focus, hover and active styles
  lib/src/tabs/Tabs.tsx
Labels: bug

#665 Added textInput types.
  docs/src/pages/components/cdk-components/text-input/api.jsx
  lib/src/number-input/NumberInputContext.js
  lib/src/number-input/NumberInputContext.tsx
  lib/src/number-input/numberInputContextTypes.ts
  lib/src/password-input/types.ts
  lib/src/slider/Slider.tsx
  lib/src/text-input/TextInput.tsx
  lib/src/text-input/types.tsx
Labels: [PR] type: Type API

#681 Added result set table types
  docs/src/pages/components/cdk-components/resultsetTable/api.jsx
  lib/src/resultsetTable/ResultsetTable.tsx
  lib/src/resultsetTable/index.d.ts
  lib/src/resultsetTable/types.ts
Labels: [PR] type: Type API

#690 [Patch] Horizontal scroll in table component
  lib/src/table/Table.tsx
Labels: bug

#672 Added toggleGroup types
  docs/src/pages/components/cdk-components/toggleGroup/api.jsx
  lib/src/toggle-group/ToggleGroup.tsx
  lib/src/toggle-group/index.d.ts
  lib/src/toggle-group/types.ts
Labels: [PR] type: Type API

#642 Added Tabs stories
  lib/src/tabs/Tabs.stories.tsx
Labels: [PR] type: visual regression

#683 Added textInput stories
  lib/src/text-input/TextInput.stories.tsx
  lib/src/text-input/TextInput.tsx
Labels: [PR] type: visual regression

#700 Added Accordion Group stories
  lib/src/accordion-group/AccordionGroup.stories.tsx
  lib/src/accordion-group/AccordionGroup.tsx
Labels: [PR] type: visual regression

#677 Adding App Layout types
  docs/src/pages/components/cdk-components/applicationLayout/ApplicationLayout.jsx
  docs/src/pages/components/cdk-components/applicationLayout/api.jsx
  lib/src/layout/ApplicationLayout.tsx
  lib/src/layout/types.ts
Labels: [PR] type: Type API

#710 Types for ThemeContext and BackgroundColorContext
  lib/src/BackgroundColorContext.tsx
  lib/src/ThemeContext.tsx
  lib/src/V3Select/V3Select.jsx
  lib/src/V3Textarea/V3Textarea.jsx
  lib/src/accordion-group/AccordionGroup.tsx
  lib/src/accordion/Accordion.tsx
  lib/src/alert/Alert.tsx
  lib/src/badge/Badge.jsx
  lib/src/box/Box.tsx
  lib/src/button/Button.tsx
  lib/src/card/Card.tsx
  lib/src/checkbox/Checkbox.tsx
  lib/src/chip/Chip.tsx
  lib/src/date-input/DateInput.tsx
  lib/src/date/Date.jsx
  lib/src/dialog/Dialog.tsx
  lib/src/dropdown/Dropdown.tsx
  lib/src/file-input/FileInput.tsx
  lib/src/file-input/FileItem.tsx
  lib/src/footer/Footer.tsx
  lib/src/header/Header.tsx
  lib/src/heading/Heading.tsx
  lib/src/input-text/InputText.jsx
  lib/src/layout/ApplicationLayout.tsx
  lib/src/link/Link.tsx
  lib/src/main.ts
  lib/src/paginator/Paginator.tsx
  lib/src/progress-bar/ProgressBar.tsx
  lib/src/radio/Radio.tsx
  lib/src/resultsetTable/ResultsetTable.tsx
  lib/src/select/Select.jsx
  lib/src/sidenav/Sidenav.tsx
  lib/src/slider/Slider.tsx
  lib/src/spinner/Spinner.tsx
  lib/src/switch/Switch.tsx
  lib/src/table/Table.tsx
  lib/src/tabs/Tabs.tsx
  lib/src/tag/Tag.tsx
  lib/src/text-input/TextInput.tsx
  lib/src/textarea/Textarea.jsx
  lib/src/toggle-group/ToggleGroup.tsx
  lib/src/toggle/Toggle.jsx
  lib/src/upload/buttons-upload/ButtonsUpload.jsx
  lib/src/upload/dragAndDropArea/DragAndDropArea.jsx
  lib/src/upload/file-upload/FileToUpload.jsx
  lib/src/upload/files-upload/FilesToUpload.jsx
  lib/src/upload/transaction/Transaction.jsx
  lib/src/upload/transactions/Transactions.jsx
  lib/src/useTheme.tsx
  lib/src/wizard/Wizard.tsx
Labels: [PR] type: Type API

#682 Adding App layout stories
  lib/.storybook/preview.js
  lib/src/layout/ApplicationLayout.stories.tsx
  lib/src/layout/ApplicationLayout.tsx
Labels: [PR] type: visual regression

#720 [Patch] Selected step when disabled style
  lib/src/wizard/Wizard.tsx
Labels: bug

#706 Fix #656: Toggle Group Icon/Label alignment
  lib/src/toggle-group/ToggleGroup.tsx
Labels: bug

#684 Added Resultset Table stories
  lib/src/resultsetTable/ResultsetTable.stories.tsx
  lib/src/resultsetTable/types.ts
Labels: [PR] type: visual regression

#696 Added Accordion stories
  lib/src/accordion-group/types.ts
  lib/src/accordion/Accordion.stories.tsx
  lib/src/accordion/types.ts
Labels: [PR] type: visual regression

#729 Added textarea types
  docs/src/pages/components/cdk-components/textarea/api.jsx
  lib/src/chip/Chip.tsx
  lib/src/chip/types.ts
  lib/src/textarea/Textarea.tsx
  lib/src/textarea/types.ts
Labels: [PR] type: Type API
