Repository dxc-technology/halstack-react, pull requests merged in 2022-03, with the labels that each got.

#743 Added file input stories
  lib/src/file-input/FileInput.stories.tsx
Labels: [PR] type: visual regression

#751 [Patch] App layout sidenav visible when scrolling
  lib/src/layout/ApplicationLayout.tsx
Labels: bug

#797 Types for Badge inner component
  lib/src/badge/Badge.tsx
  lib/src/badge/types.ts
Labels: [PR] type: Type API
