Repository dxc-technology/halstack-react, pull requests merged in 2022-07, with the labels that each got.

#1153 [Minor] Remove Inline `alignX` prop `stretch` and `baseline` values
  lib/src/inline/Inline.stories.tsx
  lib/src/inline/Inline.tsx
  lib/src/inline/types.ts
Labels: minor

#1150 Fixed quick nav container width
  website/screens/common/HeaderDescriptionCell.tsx
  website/screens/common/QuickNavContainer.tsx
  website/screens/components/accordion/code/AccordionCodePage.tsx
  website/screens/components/alert/code/AlertCodePage.tsx
  website/screens/components/alert/usage/AlertUsagePage.tsx
  website/screens/components/application-layout/code/ApplicationLayoutCodePage.tsx
  website/screens/components/box/code/BoxCodePage.tsx
  website/screens/components/button/code/ButtonCodePage.tsx
  website/screens/components/button/usage/ButtonUsagePage.tsx
  website/screens/components/card/code/CardCodePage.tsx
  website/screens/components/checkbox/code/CheckboxCodePage.tsx
  website/screens/components/chip/code/ChipCodePage.tsx
  website/screens/components/date-input/code/DateInputCodePage.tsx
  website/screens/components/dialog/code/DialogCodePage.tsx
  website/screens/components/dropdown/code/DropdownCodePage.tsx
  website/screens/components/file-input/code/FileInputCodePage.tsx
  website/screens/components/footer/code/FooterCodePage.tsx
  website/screens/components/header/code/HeaderCodePage.tsx
  website/screens/components/heading/code/HeadingCodePage.tsx
  website/screens/components/link/code/LinkCodePage.tsx
  website/screens/components/nav-tabs/code/NavTabsCodePage.tsx
  website/screens/components/number-input/code/NumberInputCodePage.tsx
  website/screens/components/paginator/code/PaginatorCodePage.tsx
  website/screens/components/password-input/code/PasswordInputCodePage.tsx
  website/screens/components/progress-bar/code/ProgressBarCodePage.tsx
  website/screens/components/quick-nav/code/QuickNavCodePage.tsx
  website/screens/components/radio-group/code/RadioGroupCodePage.tsx
  website/screens/components/radio-group/usage/RadioGroupUsagePage.tsx
  website/screens/components/resultset-table/code/ResultsetTableCodePage.tsx
  website/screens/components/select/code/SelectCodePage.tsx
  website/screens/components/select/usage/SelectUsagePage.tsx
  website/screens/components/sidenav/usage/SidenavUsagePage.tsx
  website/screens/components/slider/code/SliderCodePage.tsx
  website/screens/components/slider/usage/SliderUsagePage.tsx
  website/screens/components/spinner/code/SpinnerCodePage.tsx
  website/screens/components/switch/code/SwitchCodePage.tsx
  website/screens/components/switch/usage/SwitchUsagePage.tsx
  website/screens/components/table/code/TableCodePage.tsx
  website/screens/components/tabs/code/TabsCodePage.tsx
  website/screens/components/tabs/specs/TabsSpecsPage.tsx
  website/screens/components/tag/code/TagCodePage.tsx
  website/screens/components/text-input/code/TextInputCodePage.tsx
  website/screens/components/textarea/code/TextareaCodePage.tsx
  website/screens/components/toggle-group/code/ToggleGroupCodePage.tsx
  website/screens/components/wizard/code/WizardCodePage.tsx
Labels: bug

#1151 Added label to hamburger in application layout
  lib/src/layout/ApplicationLayout.tsx
Labels: patch

#1152 Fixed example translation
  website/screens/principles/localization/examples/translations.ts
Labels: patch

#1161 Fixed too long subtitles
  website/screens/common/HeadingLink.tsx
Labels: bug

#1156 Fixed examples overflow
  website/screens/common/example/Example.tsx
Labels: bug

#1169 Fixed small examples bug
  website/screens/common/example/Example.tsx
Labels: bug

#1168 Inline component fixes
  lib/src/inline/Inline.stories.tsx
  lib/src/inline/Inline.tsx
Labels: bug
